include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.gen.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint

linter:
  rules: